### ISSUE TITLE
Map Ripper

### ISSUE THREAD

**Issue by GhostMaree** [TheKronks/KRelay#46]
'[Error]          An exception was thrown
within ClientPacket 
at Dictionary`2.get_Item

System.Collections.Generic.KeyNotFoundException: Dany klucz nie był obecny w słowniku.
   w System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   w Lib_K_Relay.GameData.GameDataMap`2.ByID(IDType id)
   w MapRipper.JsonMap.GetTileId(UInt16 type)
   w MapRipper.JsonMap.ToJson()
   w MapRipper.Plugin.Save()
   w MapRipper.Plugin.OnSaveMapCommand(Client client, String command, String[] args)
   w Lib_K_Relay.Proxy.<>c__DisplayClass38_0.<FireClientPacket>b__0()
   w Lib_K_Relay.Utilities.PluginUtils.ProtectedInvoke(Action action, String errorProvider, Type filteredException)'

**Comment by ouaklafoud** [comment]
solved since with commit 3f8ab7d (update ushort/short in the map ripper)
